/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Complaint {
  'id' : bigint,
  'status' : Status,
  'closed' : boolean,
  'responses' : Array<string>,
  'escalated' : boolean,
  'createdAt' : bigint,
  'description' : string,
  'feedback' : [] | [Feedback],
  'updatedAt' : bigint,
  'closedAt' : [] | [bigint],
  'publicId' : string,
  'category' : string,
  'priorityScore' : PriorityScore,
  'escalatedAt' : [] | [bigint],
  'reporter' : Principal,
  'afterPhotoId' : [] | [string],
  'dueAt' : bigint,
  'location' : string,
  'photoId' : string,
}
export interface ComplaintInput {
  'description' : string,
  'publicId' : string,
  'category' : string,
  'location' : string,
  'photoId' : string,
}
export interface ComplaintResponse {
  'complaint' : Complaint,
  'publicId' : string,
}
export type ExternalBlob = Uint8Array;
export interface Feedback {
  'comment' : string,
  'rating' : [] | [bigint],
  'confirmed' : boolean,
}
export interface PriorityScore {
  'urgency' : bigint,
  'category' : string,
  'photo' : boolean,
  'location' : string,
}
export type Status = { 'resolved' : null } |
  { 'citizenConfirmed' : null } |
  { 'escalated' : null } |
  { 'open' : null } |
  { 'citizenRejected' : null } |
  { 'inProgress' : null };
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'confirmationFeedback' : ActorMethod<
    [bigint, string, [] | [bigint], boolean],
    undefined
  >,
  'duplicateCheck' : ActorMethod<[string], boolean>,
  'eskalacijaPrijave' : ActorMethod<[bigint], undefined>,
  'fetchAfterPhoto' : ActorMethod<[string], ExternalBlob>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getComplaint' : ActorMethod<[bigint], [] | [Complaint]>,
  'getComplaintsByStatus' : ActorMethod<[Status], Array<Complaint>>,
  'getOpenComplaints' : ActorMethod<[], Array<Complaint>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'publicComplaintId' : ActorMethod<[bigint], string>,
  'storeAfterPhoto' : ActorMethod<[bigint, string, ExternalBlob], undefined>,
  'storePhoto' : ActorMethod<[string, ExternalBlob], undefined>,
  'submitComplaint' : ActorMethod<[ComplaintInput], ComplaintResponse>,
  'timeLeft' : ActorMethod<[bigint], bigint>,
  'updateStatus' : ActorMethod<[bigint, Status], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];