/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Status = IDL.Variant({
  'resolved' : IDL.Null,
  'citizenConfirmed' : IDL.Null,
  'escalated' : IDL.Null,
  'open' : IDL.Null,
  'citizenRejected' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Feedback = IDL.Record({
  'comment' : IDL.Text,
  'rating' : IDL.Opt(IDL.Nat),
  'confirmed' : IDL.Bool,
});
export const PriorityScore = IDL.Record({
  'urgency' : IDL.Nat,
  'category' : IDL.Text,
  'photo' : IDL.Bool,
  'location' : IDL.Text,
});
export const Complaint = IDL.Record({
  'id' : IDL.Nat,
  'status' : Status,
  'closed' : IDL.Bool,
  'responses' : IDL.Vec(IDL.Text),
  'escalated' : IDL.Bool,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'feedback' : IDL.Opt(Feedback),
  'updatedAt' : IDL.Int,
  'closedAt' : IDL.Opt(IDL.Int),
  'publicId' : IDL.Text,
  'category' : IDL.Text,
  'priorityScore' : PriorityScore,
  'escalatedAt' : IDL.Opt(IDL.Int),
  'reporter' : IDL.Principal,
  'afterPhotoId' : IDL.Opt(IDL.Text),
  'dueAt' : IDL.Int,
  'location' : IDL.Text,
  'photoId' : IDL.Text,
});
export const ComplaintInput = IDL.Record({
  'description' : IDL.Text,
  'publicId' : IDL.Text,
  'category' : IDL.Text,
  'location' : IDL.Text,
  'photoId' : IDL.Text,
});
export const ComplaintResponse = IDL.Record({
  'complaint' : Complaint,
  'publicId' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'confirmationFeedback' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Opt(IDL.Nat), IDL.Bool],
      [],
      [],
    ),
  'duplicateCheck' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'eskalacijaPrijave' : IDL.Func([IDL.Nat], [], []),
  'fetchAfterPhoto' : IDL.Func([IDL.Text], [ExternalBlob], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getComplaint' : IDL.Func([IDL.Nat], [IDL.Opt(Complaint)], ['query']),
  'getComplaintsByStatus' : IDL.Func([Status], [IDL.Vec(Complaint)], ['query']),
  'getOpenComplaints' : IDL.Func([], [IDL.Vec(Complaint)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'publicComplaintId' : IDL.Func([IDL.Nat], [IDL.Text], ['query']),
  'storeAfterPhoto' : IDL.Func([IDL.Nat, IDL.Text, ExternalBlob], [], []),
  'storePhoto' : IDL.Func([IDL.Text, ExternalBlob], [], []),
  'submitComplaint' : IDL.Func([ComplaintInput], [ComplaintResponse], []),
  'timeLeft' : IDL.Func([IDL.Int], [IDL.Int], ['query']),
  'updateStatus' : IDL.Func([IDL.Nat, Status], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Status = IDL.Variant({
    'resolved' : IDL.Null,
    'citizenConfirmed' : IDL.Null,
    'escalated' : IDL.Null,
    'open' : IDL.Null,
    'citizenRejected' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Feedback = IDL.Record({
    'comment' : IDL.Text,
    'rating' : IDL.Opt(IDL.Nat),
    'confirmed' : IDL.Bool,
  });
  const PriorityScore = IDL.Record({
    'urgency' : IDL.Nat,
    'category' : IDL.Text,
    'photo' : IDL.Bool,
    'location' : IDL.Text,
  });
  const Complaint = IDL.Record({
    'id' : IDL.Nat,
    'status' : Status,
    'closed' : IDL.Bool,
    'responses' : IDL.Vec(IDL.Text),
    'escalated' : IDL.Bool,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'feedback' : IDL.Opt(Feedback),
    'updatedAt' : IDL.Int,
    'closedAt' : IDL.Opt(IDL.Int),
    'publicId' : IDL.Text,
    'category' : IDL.Text,
    'priorityScore' : PriorityScore,
    'escalatedAt' : IDL.Opt(IDL.Int),
    'reporter' : IDL.Principal,
    'afterPhotoId' : IDL.Opt(IDL.Text),
    'dueAt' : IDL.Int,
    'location' : IDL.Text,
    'photoId' : IDL.Text,
  });
  const ComplaintInput = IDL.Record({
    'description' : IDL.Text,
    'publicId' : IDL.Text,
    'category' : IDL.Text,
    'location' : IDL.Text,
    'photoId' : IDL.Text,
  });
  const ComplaintResponse = IDL.Record({
    'complaint' : Complaint,
    'publicId' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'confirmationFeedback' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Opt(IDL.Nat), IDL.Bool],
        [],
        [],
      ),
    'duplicateCheck' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'eskalacijaPrijave' : IDL.Func([IDL.Nat], [], []),
    'fetchAfterPhoto' : IDL.Func([IDL.Text], [ExternalBlob], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getComplaint' : IDL.Func([IDL.Nat], [IDL.Opt(Complaint)], ['query']),
    'getComplaintsByStatus' : IDL.Func(
        [Status],
        [IDL.Vec(Complaint)],
        ['query'],
      ),
    'getOpenComplaints' : IDL.Func([], [IDL.Vec(Complaint)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'publicComplaintId' : IDL.Func([IDL.Nat], [IDL.Text], ['query']),
    'storeAfterPhoto' : IDL.Func([IDL.Nat, IDL.Text, ExternalBlob], [], []),
    'storePhoto' : IDL.Func([IDL.Text, ExternalBlob], [], []),
    'submitComplaint' : IDL.Func([ComplaintInput], [ComplaintResponse], []),
    'timeLeft' : IDL.Func([IDL.Int], [IDL.Int], ['query']),
    'updateStatus' : IDL.Func([IDL.Nat, Status], [], []),
  });
};

export const init = ({ IDL }) => { return []; };